version: '3.1'

services:
  photos:
    container_name: landscaping-photos
    build: photos
    volumes:
      - ./photos/plants_photos:/plants_photos
    restart: unless-stopped
    # ports:
    #   - 6065:80

  backend:
    container_name: landscaping-backend
    build: backend
    # ports:
    #   - 6066:80
    env_file: backend.env
    restart: unless-stopped

  frontend:
    container_name: landscaping-frontend
    build: frontend
    volumes:
      # - ./frontend-config.yml:/usr/share/nginx/html/assets/config.yml
      - ./frontend-config.json:/usr/share/nginx/html/assets/assets/cfg/config.json
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    container_name: landscaping-nginx
    build: .
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - photos
      - frontend
