version: '3.1'

services:
  photos:
    container_name: landscaping-photos
    image: landscaping-photos:latest
    build: photos
    volumes:
      - ./photos/plants_photos:/plants_photos
    restart: unless-stopped
    # ports:
    #   - 6065:80

  backend:
    container_name: landscaping-backend
    image: 'landscaping-backend:0.4.2'
    build: backend
    # ports:
    #   - 6066:80
    env_file: ./backend.env
    volumes:
      - ./photos/plants_photos:/plants_photos
    restart: unless-stopped

  frontend:
    container_name: landscaping-frontend
    image: 'landscaping-frontend:1.5.1'
    build: frontend
    volumes:
      - ./frontend-config.json:/usr/share/nginx/html/assets/assets/cfg/config.json
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    container_name: landscaping-nginx
    image: 'landscaping-nginx:latest'
    build: .
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - photos
      - frontend
      - backend
