
[tool.black]
target-version = ['py310']
line_length = 120

[tool.pylint.format]
max-line-length = 120
extension-pkg-allow-list = ["pydantic"]
disable = ["duplicate-code"]

[tool.isort]
lines_after_imports = 2
multi_line_output = 3
line_length = 120
include_trailing_comma = true
