name: Test derevo method

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install library locally
        run: |
          python -m pip install --upgrade pip
          pip install -e './method[dev]'
      - name: Lint with pycodestyle
        run: |
          pycodestyle method/derevo
      - name: Test with pytest
        run: |
          pytest method
